const equiposPorGrupo = {
    "201": {
        "EQUIPO 1": [
            "ARREOLA DEVORA CAMILA RUBI",
            "FRIAS PEREZ ZAMARA GUADALUPE",
            "FUENTES RODRIGUEZ JOSE MARIA",
            "PARRA REYES MARIO MIGUEL",
            "VELASQUEZ GARCIA MARIA ISLENI",
            "VALENZUELA RAMIREZ PAOLA GUADALUPE"
        ],
        "EQUIPO 2": [
            "AVITIA REYES INGRID DENISSE",
            "BETANCOURT ALDO IVAN",
            "CAMACHO RIVERA DALIA",
            "RUIZ FRANCO JULIETA",
            "VALENZUELA VALENZUELA ANA MARIA",
            "VARGAS RETANA JOSUE ANTONIO"
        ],
        "EQUIPO 3": [
            "BENITEZ SANDOVAL XIMENA",
            "CABALLERO LOPEZ NATALIA ISABELA",
            "GALLEGOS GALLEGOS WENDY SYLEY",
            "REYES ANGEL SOL DANELI",
            "RODRIGUEZ CABALLERO JONATHAN FRANCISCO"
        ],
        "EQUIPO 4": [
            "HERNANDEZ BRIANNA ABIGAIL",
            "MARTINEZ TERRONES ELVIRA YAMILET",
            "NUÑEZ MEZA ZAHID SEBASTIAN",
            "OLGUIN CORRAL ALEXIS ARTURO",
            "PADILLA VILLEGAS MAYTE",
            "VALENZUELA MENDOZA NOEMI CAROLINA"
        ]
    },
    "202": {
        "EQUIPO DE OSCAR": [
            "SANTOS GUTIERREZ OSCAR ALEJANDRO",
            "OROZCO PAYAN RASHID ISAAC",
            "RUIZ ARREOLA PEDRO",
            "ROSAS MORALES HAZIEL",
            "ADAME NUÑEZ EDUARDO IVAN"
        ],
        "EQUIPO DE SANTIAGO": [
            "ORTEGA NEVAREZ SANTIAGO",
            "CASTRO QUIÑONES PABLO ADRIAN",
            "BARRAZA SANABRIA UBALDO DE JESUS",
            "RIVERA MARTINEZ KIMBERLY GUADALUPE",
            "ESPINOZA PRENDIS LUZ ARIANA"
        ],
        "EQUIPO DE MIGUEL ANGEL": [
            "OBREGON GONZALEZ MIGUEL ANGEL",
            "QUEVEDO MARIN FERNANDO",
            "REYES QUEZADA DIEGO",
            "CORONADO MARROQUIN DAISY ARACELY",
            "RODRIGUEZ MORENO JENNIFER MICHELL"
        ],
        "EQUIPO DE NOE": [
            "DURON FERNANDEZ ETHAN NOE",
            "DIAZ HERRERA JOSUE FERNANDO",
            "LOPEZ AYALA EFREN JOEL",
            "PAYAN NAVARRETE OSVALDO ZAMIR",
            "VELAZQUEZ SANCHEZ PAUL ESAU",
            "RIOPEDRE MARQUEZ IRVING IVAN"
        ]
    },
    "203": {
        "EQUIPO 1": [
            "VILLA RETANA ABRAHAM USIEL",
            "SOTO MARTINEZ LIZBETH",
            "RECIO DOMINGUEZ ALDO",
            "ROSAS CARBAJAL ISABELLA MADAI",
            "CANO GAMBOA BRISA ELIZABETH",
            "PIZARRO VILLA IMANOL"
        ],
        "EQUIPO 2": [
            "GURROLA PEÑA JEREMY HALIM",
            "ESTRADA GALVAN WILLIAM LEONARDO",
            "QUEBEDO VALDEZ ISAMAR",
            "MADERA REYES JOSE ARMANDO",
            "RENTERIA GARCIA FELIPE DE JESUS",
            "VAZQUEZ PIZARRO ITALY TAMARA",
            "VALENZUELA PIZAÑA ANGEL DAVID"
        ],
        "EQUIPO 3": [
            "QUEZADA GARAY JENNYFER ALINA",
            "GARCIA SALAZAR MARIA YETZALI",
            "FLORES PARRA ARLETTE",
            "GARCIA SALAZAR MAYLE LUCIA",
            "GRACIANO QUEZADA IVANA",
            "TINOCO QUIÑONES CESAR RISS",
            "DE LA ROSA NAVA OLIVER JOAN"
        ]
    },
    "204": {
        "EQUIPO 1": [
            "NEVAREZ PUGA STEISY NAHOMI",
            "REYES ORTIZ JOSELYN ARELY",
            "REYES VALENZUELA AILEEN SIOMARA",
            "REYES BARRAZA OSCAR ALONSO",
            "HERNANDEZ OBREGON MAGALY ABIGAIL",
            "RIVERA ALDAY JONATHAN AUSENCIO"
        ],
        "EQUIPO 2": [
            "LOPEZ FRANCO ELEAZAR",
            "CORRAL ARELLANO ALEXIS GIOVANY",
            "GRACIANO ANGELES JAQUELINE",
            "VALENZUELA REYES PEDRO JAVIER",
            "MARTINEZ ONTIVEROS JORDY ESAU"
        ],
        "EQUIPO 3": [
            "GRAJEDA VALDEZ SARETH ABIGAIL",
            "CHAVEZ MORONES NEFTALI JANET",
            "ENRIQUEZ MARTINEZ MARIANA LIZETH",
            "ORTIZ GUAJARDO OMALI NOHEMI",
            "REYES ROSA JOSE ISAAC",
            "AVILA BARRAZA ANGEL"
        ]
    },
    "205": {
        "EQUIPO 1": [
            "ALVARADO ROJAS ANGEL ISAIAS",
            "ROJAS CASTRO GARDENIA",
            "REYES SORIA DAYANA ALEJANDRA",
            "MAR PAYAN DULCE MAYELA",
            "FALCON QUEZADA ANGEL LEON",
            "MORALES MEDRANO ABRAHAM",
            "MUÑOZ IRIGOYEN JESUS"
        ],
        "EQUIPO 2": [
            "QUEZADA MEZA ANAMAR",
            "CABALLERO CHAIREZ PAMELA",
            "MORALES REYES REGINA",
            "LERMA SANDOVAL NATTALIA",
            "MONTES REYES JADE",
            "ALVAREZ  JOSE DE JESUS",
            "LUNA RIVAS ALEXIS SEBASTIAN"
        ],
        "EQUIPO 3": [
            "AMAYA GARCIA PAOLA MICHELTH",
            "OROZCO REYES CAMILA YAHAIRA",
            "AVILA DUARTE SEBASTIAN FERNANDO",
            "HERRERA MARTINEZ LUIS ENRIQUE",
            "ONTIVEROS ARRATIA YOCZAN ALEXANDER"
        ]
    },
    "401": {
        "EQUIPO DE AYLIN": [
            "HERRERA MARTINEZ AYLIN ARELY",
            "VILLALOBOS ORTIZ ERNESTO FROILAN",
            "GARCIA HERNANDEZ JACYD MAYLENE",
            "HERNANDEZ DEL TORO IRMA GUADALUPE",
            "NUÑEZ ZUÑIGA JESUS ALBERTO",
            "NIEVES ESCOBEDO XIMENA AIDE",
            "DOMINGUEZ ONTIVEROS WILLIAM"
        ],
        "EQUIPO DE LUIS": [
            "GOMEZ FRANCO LUIS ANGEL",
            "QUIÑONEZ CASTRO JUAN JACIEL",
            "QUIÑONES ALMODOVAR ERICK JESSUI",
            "VALLES NORIEGA ZLATAN KARIM",
            "IBARRA CALLEROS EVELYN GUADALUPE",
            "AVITIA RAMIREZ AZUL DANAE"
        ],
        "EQUIPO DE JAVIER": [
            "VAZQUEZ SOTO VALENTIN",
            "HERNANDEZ MARTINEZ JESUS JAVIER",
            "NUÑEZ AYALA ABEL EDUARDO",
            "CARBAJAL SANCHEZ JOEL ANTONIO",
            "PEREZ IBARRA ISIDRO DAVID"
        ],
        "EQUIPO DE BRANDON": [
            "LOPEZ ORTIZ ALAN JESUS",
            "RAMIREZ ORTIZ JAIRO YOSEP",
            "SIDA MALDONADO JOSE MARIA",
            "RAMIREZ RODRIGUEZ HECTOR MANUEL",
            "IRIGOYEN QUIÑONES BRANDON",
            "HUERTA MARTINEZ CAROLINA ESPERANZA"
        ]
    },
    "402": {
        "SIN EQUIPO REGISTRADOS": [
            "Sin alumnos registrados"
        ]
    },
    "403": {
        "EQUIPO DE YUSEI": [
            "GURROLA ANTUNA JULIO ISMAEL",
            "GURROLA ANTUNA CESAR ISAAC",
            "HERRERA REYES EDWIN",
            "ALVAREZ REYES LEONARDO",
            "RIVAS VELAZQUEZ GERARDO ISAAC",
            "ZEGER VASQUEZ YUSEI",
            "CHAVEZ REYES ORLANDO ALBERTO"
        ],
        "EQUIPO DE KIMBERLY": [
            "RODRIGUEZ CARRAZCO MIRIAM",
            "AYALA GONZALEZ KRITZIA LILY",
            "VALENZUELA MENDOZA MAYTE V",
            "AVILA BERMUDEZ DAFNE ALEJANDRA",
            "GARAY VALENZUELA KIMBERLY",
            "ACOSTA HERNANDEZ DIEGO",
            "DIAZ HUERTA MARIA FERNANDA"
        ],
        "EQUIPO DE JIMENA": [
            "SANTOS HERRERA JIMENA",
            "PIÑA ARCINIEGA ALLISSON RENATA",
            "COLIN SARABIA XANA CAMILA",
            "BERNAL SARIÑANA GUILLERMO ANTONIO",
            "GARCIA LUNA MANUEL ERNESTO",
            "REYES ESTRADA GENESIS YOMARA"
        ],
        "EQUIPO DE ALONSO": [
            "RIVAS ALVARADO ULISES ALONSO",
            "TERRAZAS ACOSTA HANNA YISEL",
            "GALVAN RETANA MISAEL",
            "GALINDO FRANCO JUAN MANUEL",
            "GALINDO NORIEGA MICAELA G",
            "GONZALEZ DIAZ KEIRA ABRIL",
            "CASTRO ROCHA SANTIAGO OSCAR",
            "MORALES CANAAN JAVIER"
        ]
    },
    "404": {
        "EQUIPO 1": [
            "FUENTES GONZALEZ DULCE MARIA",
            "MORALES DIAZ CAMILA",
            "VELAZQUEZ GUTIERREZ VICTORIA",
            "DIAZ ACOSTA ANGELA BENNET",
            "GALINDO CRUZ PAOLA MATZIEL",
            "GONZALEZ SOTO SOFIA JOSELYN"
        ],
        "EQUIPO 2": [
            "ORONA CAMPOS XIMENA",
            "SANDOVAL CAMPOS EMELY GUADALUPE",
            "GALLEGOS GARCIA JULIA",
            "ROMERO HERNANDEZ JOHANA RUBI",
            "GARCIA DIAZ ESTRELLA",
            "ARELLANO SANTILLAN SARA"
        ],
        "EQUIPO 3": [
            "FRANCO QUIÑONES MIGUEL ALONSO",
            "CHAVEZ QUINTERO BELEN GUADALUPE",
            "REYES IRIGOYEN PALOMA YAMILE",
            "ALDABA QUEZADA SERGIO ALEJANDRO",
            "SANCHEZ SOTO SAHAMANTHA SUSSEY"
        ],
        "EQUIPO 4": [
            "OBREGON GURROLA KITZIA PALOMA",
            "REYES FERNANDEZ DANITZIA GUADALUPE",
            "REYES GONZALEZ BRAYAN EDUARDO",
            "RAMOS CALDERA ROMAN JAIR",
            "ALAMILLO INSURRIAGA JUAN AGUSTIN",
            "AYALA ARREOLA JOSUE MANUEL",
            "VILLASENOR MENDOZA TANYA GUADALUPE"
        ],
        "EQUIPO 5": [
            "NIEVES GARCIA JOSE MANUEL",
            "SIDA DOMINGUEZ LILIANA",
            "VILLARREAL HERRERA BRIANA",
            "ROJAS RIVERA XIMENA",
            "PEREZ SANDOVAL MIGUEL ANGEL",
            "DIAZ NIEVES DANIELA ANAHI"
        ]
    },
    "405": {
        "EQUIPO DE ESMERALDA": [
            "ESPARZA ARREZ JOSE EDUARDO",
            "PAEZ ALVAREZ ESMERALDA JOSELINE",
            "CONTRERAS SARIÑANA LUIS MANUEL",
            "RODRIGUEZ PIZARRO KEVIN ADRIAN",
            "CIGARROA ORTIZ ANGELICA",
            "BLANCO NEVAREZ ORLANDO",
            "GUERRERO ARANGO NAHOMI ABIZAI"
        ],
        "EQUIPO DE ELIAN": [
            "GARCIA RAMOS ELIAN YAEL",
            "GARCIA MORALES EFREN FERNANDO",
            "ARGUMEDO GARCIA EVELYN",
            "RODRIGUEZ RAMIREZ OSCAR GAEL",
            "ANDRADE NEVAREZ ANTONIO ITAMAR",
            "ORTIZ BURCIAGA JOSE ANGEL",
            "FAVELA PEREDA CRISS ANGEL"
        ],
        "EQUIPO DE XIMENA": [
            "NUÑEZ GARCIA EDITH",
            "LARA GONZALEZ ALISSON DANAE",
            "AGUIRRE AVILA ANGEL HASSAN",
            "REYES CASTAÑEDA XIMENA",
            "ARELLANO SANTILLAN DIANA",
            "RAMIREZ PONCE EDGAR TADEO",
            "QUIROGA MARTINEZ GAEL",
            "SORIA AVITIA OWHEN IVAN"
        ],
        "EQUIPO DE KAMILA": [
            "ONTIVEROS CHAVEZ KAMILA",
            "CONTRERAS CHAIREZ JUAN PEDRO",
            "PEREZ ORTIZ LUZ ARELI",
            "FLORES CEBALLOS RODRIGO",
            "SIFUENTES MORALES WILLIAM ISAAC"
        ]
    },
    "406": {
        "EQUIPO 1": [
            "RODRIGUEZ GALLEGOS INGRID DENISE",
            "REYES RODRIGUEZ KETZUVY YARELY",
            "VALENZUELA HUERTA CAMILA",
            "SARIÑANA PINEDO KAROL XIMENA",
            "DEL TORO FAVELA LOVELY ENID",
            "GRACIANO ENRIQUEZ LILIANA NOHEMI"
        ],
        "EQUIPO 2": [
            "RENTERIA PEREZ ESTRELLA GUADALUPE",
            "MARTINEZ RIVERA ELIZABETH",
            "PEREZ ROSAS MARIO ALBERTO",
            "MORALES VARGAS JIMENA",
            "TERRAZAS ANA GUADALUPE",
            "SANDOYA BARRON CAMILA ARALY"
        ],
        "EQUIPO 3": [
            "MORALES VALENCIANA ALYSON GUADALUPE",
            "REYES SANCHEZ ANAHI",
            "LUNA TORRES ANDREA SUGEY",
            "PIZAÑA FRANCO KEVIN EDUARDO",
            "LUNA GRAJEDA ELIUD ASHAEL"
        ],
        "EQUIPO 4": [
            "CHAVARRIA ROJAS DANIELA GUADALUPE",
            "PARRA SEGOVIA KASSANDRA",
            "PIZARRO ACOSTA NEIDA GUADALUPE",
            "CAMPOS GARCIA MARIA JOSE"
        ],
        "EQUIPO 5": [
            "ALVARADO FUENTES HELEN MARINA",
            "CORRAL DURON KETZALY ESTRELLA",
            "HERNANDEZ SOTO BRISSA",
            "DIAZ VARGAS XIMENA SOCORRO",
            "VALADEZ HERNANDEZ WILLIAM ALEJANDRO",
            "CHAVEZ DIAZ DIEGO ANGEL",
            "RODRIGUEZ GURROLA FERNANDA SARAHI"
        ]
    }
};
